### ISSUE TITLE
Support for vagrant

### ISSUE THREAD

**Issue by Nithanim** [infertux/zeyple#18]
I made a build-script for vagrant to be able to setup a test environment with only one command.
You can find it on this branch: https://github.com/Nithanim/zeyple/tree/vagrant I am still getting the hang of cross-repository-interaction and I don't want to merge my branch directly into master. How would I issue a pull request in the best way?

**Comment by infertux** [comment]
Nice! I think it makes more sense to keep the Vagrant setup out of the main repository, especially since it's a test environment. I would suggest you create your own `zeyple-vagrant` repo (for example) and then link to it from https://github.com/infertux/zeyple/blob/master/CONTRIBUTING.md and maybe copy [this paragraph](https://github.com/Nithanim/zeyple/blob/7c6c997b267b6476329d9473ff72a3b86101be5b/README.md#vagrant) there. You can either send me a pull request or a Git patch for that, whatever is easier for you. Thanks! :)

By the way, I created a [separate repo](https://github.com/infertux/chef-zeyple) for similar purposes. I'd like to keep this main repo as small as possible.

**Comment by Nithanim** [comment]
Ah, thank you. That was actually the solution I was looking for but could not think of that for some reason. That must be it why the branch always felt wrong to me. :)
